### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by yuri-becker**
The specified yt-dlp version (or whichever the build ships with) is not able to download videos from youtube anymore (401 errors - probably some api change). Simply works again with the newest version. Also youtube-search-python was missing in the requirements.txt.

### CODE REVIEW

**Comment by noodleneck1** [comment]
Is there any chance you could package this like the previous version by stripedew? Thank you.

**Comment by yuri-becker** [comment]
@noodleneck1 Yea, I will look into it. I changed some more things on my fork so that hopefully the tool runs more reliable, once I get around to testing it properly I can just package my fork. 
Honestly would still prefer it if @stripedew merged this PR, but if they're gone, I'd be happy to keep maintaining it.

**Comment by stripedew** [comment]
Funny timing as I very recently went back to CH and noticed the tool wasn't working and was going to update it. Only to realise this account had notifications off and I missed these posts.

Thanks for the pull request @yuri-becker and tagging me, I've merged it now and I will compile an executable once I'm back home in a few days @noodleneck1 :)

**Comment by stripedew** [comment]
@noodleneck1 I have packaged the file into an .exe again, let me know if it works!

**Comment by noodleneck1** [comment]
> @noodleneck1 I have packaged the file into an .exe again, let me know if it works!

Seems to work perfectly, thanks!

**Pull request merged**
